#!/bin/bash

# http://itnotesandscribblings.blogspot.com/2014/08/firewalld-adding-services-and-direct.html

sudo firewall-cmd --zone=public --add-interface=eth0

sudo firewall-cmd --get-zone-of-interface=eth0

sudo firewall-cmd --list-services

sudo firewall-cmd --get-services

sudo firewall-cmd --permanent --add-service=ssh
sudo firewall-cmd --permanent --add-service=http
sudo firewall-cmd --permanent --add-service=https

