# see: http://docs.ansible.com/intro_patterns.html

# You can also specify the intersection of two groups. This would mean the hosts must be in the group webservers and the host must also be in the group staging:

# You can also use variables if you want to pass some group specifiers via the “-e” argument to ansible-playbook, but this is uncommonly used:

- hosts: tag_Project_{{ project_name }}:&tag_Environment_{{ aws_environment }}:&tag_Group_{{ group_name }}
  sudo: True
  connection: "{{ connection_type }}"
  gather_facts: yes

  vars_files:
    - group_vars/tag_Project_{{ project_name }}
    - group_vars/tag_Environment_{{ aws_environment }}
    - group_vars/tag_Group_{{ group_name }}

  roles:
    - common
    - utils
    - applications/tomcat

