#!/bin/bash

os_release=`lsb_release -is`

# install epel
if [ $os_release = "RedHatEnterpriseServer" ]
then 
    echo "installing epel via rpm call for RHEL"
    sudo rpm -Uvh http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
elif [ $os_release = "CentOS" ]
then 
    echo "installing epel via yum for CentOS"
    sudo yum install -q -y epel-release
fi

# manually install jinja2 if RHEL
if [ $os_release = "RedHatEnterpriseServer" ]
then 
    echo "RHEL detected. Manually installing jinja2..."
    sudo rpm -Uvh ftp://mirror.switch.ch/pool/4/mirror/scientificlinux/6.6/x86_64/os/Packages/python-jinja2-2.2.1-2.el6_5.x86_64.rpm
fi

# install ansible 1.8, create user
echo "installing ansible"
sudo yum install -q -y ansible
sudo useradd ansible --uid 9393

#install cowsay.  makes ansible output pretty.
sudo yum -q -y install cowsay

# install sshpass
echo "installing sshpass"
sudo yum install -q -y sshpass

# add admin group, add myself to the admin group
sudo groupadd --gid 7777 admin
sudo usermod -a -G admin `whoami`

# generate ansible keypair
if sudo [ -f ~ansible/.ssh/id_rsa ] 
then
    echo "keypair already exists for ansible, doing nothing."
else
    echo "creating keypair for ansible. DO NOT ENTER A PASSPHRASE."
    sudo -u ansible -s /usr/bin/ssh-keygen -q -t rsa -C ansible@cablevision.com
fi

# generate keypair for me, which will be added to the authorized_keys for ansible account
if [ -f ~/.ssh/id_rsa ] 
then
    echo "keypair already exists for `whoami`, doing nothing."
else
    echo "creating keypair for `whoami`"
    myemail="`whoami`@cablevision.com"
    ssh-keygen -t rsa -C $myemail
fi
