
# provision.xml will precede this
# within this you'll see the vsphere guest calls.

# Apply common configuration to all hosts
- hosts: all
  user: root
  roles:
    - common

# show DNS interactions against dev bind. eric current owner.

# configure and deploy jboss server(s).
- hosts: webservers
  user: root
  roles:
    - jboss

# Configure and deploy the load balancer(s).
- hosts: lbservers
  user: root
  roles:
    - haproxy # basic installation working. need to ensure that it works with jboss. greg current owner.
    # - ssl_certs # eric to implement this, self-signed for first round...