---
# This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  user: root
  roles:
    - common

# configure and deploy jboss server(s).
- hosts: webservers
  user: root
  roles:
    #- base-apache
    #- web
    - jboss

# Configure and deploy the load balancer(s).
- hosts: lbservers
  user: root
  roles:
    - haproxy
