
# NOTES FOR BENNO
# benno, here's some basics that we've worked out for the initial install. 
# note that we are using haproxy while we get the f5 infrastructure worked out. 
# what would be helpful is some example code that would precede what you see, that shows us a 'best practice' for provisioning and configuring vsphere guests.
# thanks, greg

# Apply common configuration to all hosts
- hosts: all
  user: root
  roles:
    - common

# show DNS interactions against dev bind. eric current owner.

# configure and deploy jboss server(s).
- hosts: webservers
  user: root
  roles:
    - jboss # naveen to implement this. single configuration file for cluster configs should be deployed along with installed pacakges.
    # - ssl_certs # eric to implement this, self-signed for first round...

# Configure and deploy the load balancer(s).
- hosts: lbservers
  user: root
  roles:
    - haproxy # basic installation working. need to ensure that it works with jboss. greg current owner.
