---
- hosts: local
  connection: local
  sudo: false
  gather_facts: false
  tasks:
  - name: generate self signed SSL certificate
    command: /home/emcalvin/ansible-playbooks/roles/ssl-cert/files/generate_ssl_selfsigned.sh '{{fqdn}}' '{{short_name}}' '{{cert_length_years}}' 
    register: ssl_cert_pem_filename

