
#- name: ensure networkmanager is deactivated
#  service: name=NetworkManager state=stopped enabled=no
#  when: 

- name: ensure several packages are installed
  yum: name={{ item }} state=latest
  with_items:
    #- epel-release
    #- git
    #- emacs-nox
    - htop
    #- python-pip
  tags:
    - packages

- name: be sure ntp is installed
  yum: pkg=ntp state=installed
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp

