
#- name: ensure networkmanager is deactivated
#  service: name=NetworkManager state=stopped enabled=no
#  when: 
#    ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 7

#- name: ensure epel is installed
#  command: /bin/rpm -Uvh http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

- name: ensure several packages are installed
  yum: name={{ item }} state=latest
  with_items:
    - epel-release
  tags:
    - packages

#- debug: msg="{{ansible_os_family}}"
#- debug: msg="{{ansible_lsb.major_release}}"

- name: ensure several OTHER packages are installed, that only work on RedHat 7+
  yum: name={{ item }} state=latest
  with_items:
    - htop
  when: 
    ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 7
  tags:
    - packages

- name: be sure ntp is installed
  yum: pkg=ntp state=installed
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp

