
- name: ensure networkmanager is deactivated
  service: name=NetworkManager state=stopped enabled=no

- name: ensure several packages are installed
  yum: name={{ item }} state=latest update_cache=true
  with_items:
    - epel-release
    - git
    - git-core
    - emacs-nox
    - htop
    - python-pip
  tags:
    - packages

- name: custom etc/issue
  template: src=issue.j2 dest=/etc/issue owner=root

### NTP

- name: be sure ntp is installed
  yum: pkg=ntp state=installed
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp

### END NTP


