---
- hosts: local
  connection: local
  sudo: true
  gather_facts: false
  tasks:
  - name: get next available ip and add newly provisioned host to dns
    command: /home/emcalvin/ansible-playbooks/roles/dns-record/files/add_dns_wrapper.sh '{{ start_ip }}' '{{end_ip}}' '{{server_name}}' 
    register: new_host_ip
