---
- name: add_dns_record
  sudo: true
  #gather_facts: false
  command: /home/emcalvin/ansible-playbooks/roles/dns-record/files/add_dns_wrapper.sh '{{ start_ip }}' '{{end_ip}}' '{{server_name}}' 
  register: new_host_ip
- name: Show the IP we registered in DNS.
  debug: msg="{{ server_name }} {{ new_host_ip.stdout }}"
